### ISSUE TITLE
Clarify that registerPartials is async

### ISSUE THREAD

**Issue by sameoldmadness** [pillarjs/hbs#123]
It's still unclear that `registerPartials` is async.

I've just bumped into nasty race conditions because I've called this method as syncronous (as it is used in a readme example).

It would be nice to add a couple of lines describing one should provide callback to be sure partials are registered before rendering.

Related to #68 #71

**Comment by defunctzombie** [comment]
Hm. Need to double check the original PR on this but this seems to me that it would be incorrect behavior based on both the example in the readme and how the other registerPartials method behaves.

Would accept a PR to fix this up.
