### ISSUE TITLE
add options ‘min’ to output compressed result

### ISSUE THREAD

**Issue by dtboy1995** [pillarjs/hbs#139]
hello master, i love your module,i used it in a number of projects, but for production ,best to compress and min the output, i hope you can add the option to the module, thanks very much. thanks thanks.

**Comment by dougwilson** [comment]
Hi @dtboy1995 this is just a simple module to wrap the https://github.com/wycats/handlebars.js module to the Express.js view engine. You would need to get that feature added in the handlebars.js module and then we can easily expose the functionality here.
