### ISSUE TITLE
registerAsyncHelper production bug when no layout.hbs is used

### ISSUE THREAD

**Issue by priedthirdeye** [pillarjs/hbs#140]
If running in production mode without the use of a layout.hbs file, AsyncHelpers only work the first time, After the first request, the callback function doesn't execute so the random string gets rendered to the page.

```
// Code Demonstrating registerAsyncHelper Bug

app.set('env', 'production');
var hbs = require('hbs');

// Basic async helper for demo
hbs.registerAsyncHelper('getTimeInThisManySeconds', function(secondsToWait, options, callback) {   
  setTimeout(function(){
    callback(options.fn({secondsToWait: secondsToWait, theTime: new Date(), mode: app.get('env')}))
  }, secondsToWait * 1000);  
});
```

```
<p>Welcome to {{title}}</p>
{{#getTimeInThisManySeconds '2'}}
We waited {{secondsToWait}} seconds and it is now {{theTime}}.
<br><br>
We are currently in <b>{{mode}}</b> mode.
{{/getTimeInThisManySeconds}}
```

This will work in repeatedly if there is a layout file present. It won't work after the first request if there is no layout file present. 

Possible Solution:

It looks like your `render_file` function needs to call `self.async.done` even when the file is loaded from cache.

**Comment by adyz** [comment]
I have a similar problem and my server says: not sure if this is related...


```

Error: Cannot find module 'foreachasync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /node_modules/hbs/node_modules/walk/lib/walk.js:8:22
    at Object.<anonymous> (/node_modules/hbs/node_modules/walk/lib/walk.js:301:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

**Comment by dougwilson** [comment]
Sorry this sat around for so long. I am not maintaining this module and have been going through the issues and pull requests. It looks like PR #141 actually fixes this very thing, and I'm getting it merged. I guess better late than never 😂
