### ISSUE TITLE
Unable to add css files with handlebars

### ISSUE THREAD

**Issue by soumik12345** [pillarjs/hbs#149]
How do I add css files to a handlebars file and how do I set the relative path of a css file in case of a css file in the local directory?

**Comment by dougwilson** [comment]
Hi @soumik12345 , sorry this repository has been lingering for a while. Handlebars is just a HTML template language, so you generate HTML to reference your CSS files (like using a `<link>` tag). Here is a good answer for what I believe your question is: https://stackoverflow.com/questions/45395947/what-is-the-proper-way-of-referencing-css-and-js-files-with-handlebars

**Comment by omkushwaha14** [comment]
> [``](facebook.com)

**Comment by kiranpoojary** [comment]
1)first u need to install bootstrap in(bootstrap package will install in node_module directory ): 
$ **npm install bootstrap --save**
<br>
2)**Set your app.js** (Server.js/appStart.js) file like in the bellow image at line number 28.


![appStart](https://user-images.githubusercontent.com/36165693/92324911-bf4acb80-f063-11ea-9414-33ce5c599a05.PNG)
<br>
3)**Import your .css file** in mainlayout handlebar or normal handlebar file like given in bellow image
![mainLayout](https://user-images.githubusercontent.com/36165693/92324998-a4c52200-f064-11ea-9a2c-d531c2fb14de.PNG)

**Note**: If you add the .css file in main layout then no need to add the same .css file again in child layout .
