### ISSUE TITLE
Ensure that cache is used

### ISSUE THREAD

**Issue by ORESoftware** [pillarjs/hbs#152]
I am looking into this issue:
https://github.com/expressjs/express/issues/3639#issuecomment-385721621

my concern is that when we call

```js
res.render('index.hbs');
```

that it's not caching the compiled template.
Ideally, it will read from the filesystem once and compile the template just once. So that would be:

```js
const file = fs.readFileSync('index.hbs');  
const render = Handlebars.compile(file);  // we will want to cache this render function
render({foo: 'bar'});
```

but in testing this thing, I have noticed that it's possible that the cache is not being used either by Express or by hbs.

How can I ensure that cache gets used and that:

1. Reading the template from the filesystem
2. Compiling the template

Happen just once?

**Comment by markstos** [comment]
@ORESoftware Can you provide steps to reproduce to confirm that caching *isn't* happen with `hbs` currently?

**Comment by ORESoftware** [comment]
@markstos to get view caching in Express, you have to do some variant of:

```js
app.set('view cache', true);
```

I think it was an Express issue
