### ISSUE TITLE
Solving 'Partial xxxx not found'

### ISSUE THREAD

**Issue by webtop** [pillarjs/hbs#159]
I was having issues with this and solved it by adding some console logging in the hbs.js file, in the register function inside of registerPartials.

Simply console.log(filepath) and make sure it makes sense.

HTH

**Comment by dougwilson** [comment]
Hi @webtop hello! I am trying to help with maintenance on this repo and am going through open issues today.

I'm not quite sure, is this an issue report, a general question, or something else? I guess my question is I'm not clear how I can help here. Please let me know, thank you!

**Comment by webtop** [comment]
Hey Doug,

I saw this error message come up on some older reports, so just wanted to post this in case anyone else came across this. I would have posted to the wiki, but don't see one.

I thought I had already closed it.

Thanks.
