### ISSUE TITLE
High severity vulnerability found [AGAIN] - Prototype pollution attack

### ISSUE THREAD

**Issue by iwaduarte** [pillarjs/hbs#163]
https://github.com/pillarjs/hbs/issues/162
This issue that it was solved pointing to handlebars 4.0.13 now it is considered vulnerable by snyk also.
 ✗ High severity vuln found in handlebars@4.0.13, introduced via hbs@4.0.3
    Description: Prototype Pollution
    Info: https://snyk.io/vuln/SNYK-JS-HANDLEBARS-174183
    From: hbs@4.0.3 > handlebars@4.0.13 **[ A matter of changing the pack json from 4.0.13 to 4.0.14]**

Could we try and fix this?

**Comment by iwaduarte** [comment]
Remediation
Upgrade handlebars to version 4.1.2, 4.0.14 or higher

**Comment by dougwilson** [comment]
I'll get it bumped and released here in a few minutes(ish).

**Comment by dougwilson** [comment]
Published as version 4.0.4
