### ISSUE TITLE
Handlebars: Access has been denied to resolve the property "statements" because it is not an "own property" of its parent.

### ISSUE THREAD

**Issue by paradoxina** [pillarjs/hbs#187]
need update!  fix production error 
```
Handlebars: Access has been denied to resolve the property "statements" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning: ....
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
...
```
problem description
[https://github.com/facebook/jest/issues/9396](https://github.com/facebook/jest/issues/9396)

**Comment by dougwilson** [comment]
Thank you for the report, but it's unclear to me what, specifically, this module should be doing different. I looked at the link, and I don't see any mention of this module (`hbs`), only of a different module `handlebars`. Did you file this issue at the right location? If so, perhaps can you provide a reproduction case using this module to demonstrate the issue you're having?

**Comment by paradoxina** [comment]
I only had a problem in production, 
`Handlebars: Access has been denied to resolve the property "statements" because it is not an "own property" of its parent.`
everything is fine in dev
until I clearly pointed to the `"handlebars": "~4.5.3"`, in `packege.json`
```
...
"hbs": "^4.1.0",
"handlebars": "~4.5.3",
...
```
somehow my server was using the latest version in prod  `"handlebars": "^4.5.3"` `4.7.0`


I may have a problem, since you have explicitly indicated 
```
"dependencies": {
    "handlebars": "4.5.3",
    "walk": "2.3.14"
  },
```


thanks for the quick response, if I have the problem, issue can be closed

**Comment by dougwilson** [comment]
Hi @paradoxina I apologize, as I'm still unclear what the issue is, though it sounds like it is unrelated to this module.
