### ISSUE TITLE
Handlebars 4.7.3

### ISSUE THREAD

**Issue by jbondia** [pillarjs/hbs#188]
Hi all,

Is the library compatible with the latest version on Handlebars? I am double checking because `handlebars 4.6.0` has breaking changes even though they only increased the minor version. https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v460---january-8th-2020

Thank you!

**Comment by jonchurch** [comment]
The version of handlebars this package uses is `4.5.3`.

That being said, I updated to latest handlebars `4.7.3` and ran the test suite and everything passed. But to be clear, when you install this package it will pull down handlebars `4.5.3`.
