### ISSUE TITLE
Low security on minimist

### ISSUE THREAD

**Issue by badrddinb** [pillarjs/hbs#189]
Low: Prototype Pollution
Package: minimist
Patched in: >=0.2.1 <1.0.0 || >=1.2.3
Dependency of: hbs
Path: hbs>handlebars>optimist>minimist
More info: https://npmjs.com/advisories/1179

**Comment by dougwilson** [comment]
Looks like there is no quick fix. The 4.x series of handlebars has no solution unless their sub dependency updates (optimist), though it is gone in handlebars 5.x. What the major upgrade will entail needs to be evaluated and likely will require a major upgrade here and then in consumers of this module.

If you are looking for a quick resolution, a new optimist module would fix it.

**Comment by dougwilson** [comment]
Also looks like handlebars 4.x has ongoing work to provide a 4.x release without the issue: https://github.com/wycats/handlebars.js/pull/1662

**Comment by badrddinb** [comment]
Now i see why is this happens. I think i will use handlebars 5.x instead! thank you.

**Comment by badrddinb** [comment]
So I think the best option to switch to another view-engine till handlebars fix this issue.
