### ISSUE TITLE
Outdated dependency 'minimist'

### ISSUE THREAD

**Issue by TanishqSingla** [pillarjs/hbs#190]
When I checked yarn.lock file there was a dependency minimist which is set to version 0.0.1, this is giving security alert when uploaded on github, can you do something about it

**Comment by dougwilson** [comment]
I have to wait for our direct dependency to land and release this PR: https://github.com/wycats/handlebars.js/pull/1662

**Comment by TanishqSingla** [comment]
I appreciate your quick response but it seems like I won't be able to use handlebars until the PR. I hope the issue gets resolved

**Comment by dougwilson** [comment]
No problem :) if you have another solution, you are welcome to make a pull request, but otherwise as far as I can tell there us nothing I can change on this module to address your issue.
