### ISSUE TITLE
Security Contact Needed

### ISSUE THREAD

**Issue by agustingianni** [pillarjs/hbs#197]
Hello,

I am a member of the GitHub Security Lab (https://securitylab.github.com).

I've attempted to reach a maintainer for this project to report a potential security issue but have been unable to verify the report was received. Please could a project maintainer contact us at securitylab@github.com, or provide an email address so we can contact you.

Thank you,
Agustin Gianni (@agustingianni)
GitHub Security Lab

**Comment by dougwilson** [comment]
Thanks for the message.i am the main maintainer these days and didn't recieve any email so far from you (I believe). I just sent an email to that address to reach out.

**Comment by dougwilson** [comment]
Actually @agustingianni I did recieve an email from you on Monday. There were a few reports attached, but nothing for `hbs`, so I didn't respond. Looking back I see you sent a follow up email with one, and I missed that follow up, I'm sorry. I have it now.
