### ISSUE TITLE
CSS not loaded when more than one '/' in the path

### ISSUE THREAD

**Issue by aetrnm** [pillarjs/hbs#206]
I have a 404 page route (code below). It works perfectly well with my 404.hbs file, css loads as well when I access **localhost:3000/nonexistingpath**
```
app.get("*", (req, res) => {
  res.render("404", {
    heading: "404",
    errorMessage: "Page not found",
    author: "me",
  });
});
```

However, css doesn't get loaded when I try to access **localhost:3000/non/existing/path**

**Comment by dougwilson** [comment]
Hello, and sorry you are having that issue. It is unfortunately not related to this module, as it is just basic HTML. You need ti use an absolute path to your CSS in your HTML for your use case to work.
