### ISSUE TITLE
Issue with Async Helpers on Heroku

### ISSUE THREAD

**Issue by davidkaneda** [pillarjs/hbs#67]
I'm getting the ID/hash (`__af2oij3__`) rendering for async helpers when I put my app on Heroku, but not locally. Just wondering if anyone else has run into this and has some ideas... Sorry I don't have more details to explain why it's happening. Is there a timeout that it gives on trying to replace the IDs after?

**Comment by vkareh** [comment]
This is still an issue. When `NODE_ENV` is set to production, express automatically sets `view cache` to true. Async helpers set an ID that gets replaced by the resolved value, however this only happens on the non-cached version of the template. As soon as the template gets cached, the IDs no longer get replaced. See my pull request #124 for a fix that replaces the async IDs for both cached and non-cached templates.
