### ISSUE TITLE
Raw block not working.

### ISSUE THREAD

**Issue by okvic77** [pillarjs/hbs#81]
I have raw code to be printed, I'm working with Angular too. I create a custom block helper called raw, and {{string}} like this works good, but string like {{modulo.editing ? 'Editando':'Salir' }} goes wrong.

```
hbs.registerHelper('raw', function(name, context) {
    return name;
});
```

```
{{{raw '

My HTML code for {{angular}} but goes wrong with {{anyBool?'ok':'Not'}}.

' }}}
```

Is there any way for {{raw}} All my stuff {{/raw}}

Thanks.

**Comment by cfjedimaster** [comment]
I'm running into this as well. According to the Handlebar docs, if you do {{{{raw-helper}}}} .. {{{{/raw-helper}}}} the content will be ignored. But when I request my HTML page the content inside is being *removed* by hbs, not ignored.

**Comment by cfjedimaster** [comment]
I stand corrected - adding the helper makes it work. Sorry.
